-- ==========================================
-- SCRIPT DE CONFIGURACIÓN PARA SUPABASE
-- ==========================================
-- Copia y pega este script en el SQL Editor de tu proyecto de Supabase
-- para crear la tabla de productos y habilitar las funciones seguras.

-- 1. Crear la tabla de productos
CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    image TEXT,
    icon TEXT,
    price TEXT
);

-- 2. Habilitar la Seguridad a Nivel de Fila (RLS)
ALTER TABLE products ENABLE ROW LEVEL SECURITY;

-- 3. Crear política para permitir que CUALQUIER persona lea los productos
-- (Para que los visitantes de tu web puedan ver el catálogo)
DROP POLICY IF EXISTS "Allow public read access" ON products;
CREATE POLICY "Allow public read access" ON products 
    FOR SELECT USING (true);

-- 4. Nota sobre Seguridad:
-- Al activar RLS y no crear políticas de INSERT/DELETE directas, nadie podrá
-- modificar la base de datos usando el API Key público desde la consola.
-- Las modificaciones solo podrán hacerse mediante las funciones RPC de abajo.

-- 5. Crear función RPC segura para AGREGAR un producto (verifica el hash de la contraseña)
CREATE OR REPLACE FUNCTION add_product_secure(
    p_password_hash TEXT,
    p_title TEXT,
    p_description TEXT,
    p_image TEXT,
    p_icon TEXT,
    p_price TEXT DEFAULT NULL
) RETURNS VOID SECURITY DEFINER AS $$
BEGIN
    -- Compara el hash enviado con el hash maestro de 'geekhaus2026'
    IF p_password_hash = 'bb6478238080e4322cccf4a6f501bccf48564adb54aa1ec8a073411ad9807329' THEN
        INSERT INTO products (title, description, image, icon, price)
        VALUES (p_title, p_description, p_image, p_icon, p_price);
    ELSE
        RAISE EXCEPTION 'No autorizado: Hash de contraseña incorrecto';
    END IF;
END;
$$ LANGUAGE plpgsql;

-- 6. Crear función RPC segura para ELIMINAR un producto (verifica el hash de la contraseña)
CREATE OR REPLACE FUNCTION delete_product_secure(
    p_password_hash TEXT,
    p_id BIGINT
) RETURNS VOID SECURITY DEFINER AS $$
BEGIN
    -- Compara el hash enviado con el hash maestro de 'geekhaus2026'
    IF p_password_hash = 'bb6478238080e4322cccf4a6f501bccf48564adb54aa1ec8a073411ad9807329' THEN
        DELETE FROM products WHERE id = p_id;
    ELSE
        RAISE EXCEPTION 'No autorizado: Hash de contraseña incorrecto';
    END IF;
END;
$$ LANGUAGE plpgsql;
